/* =========================================================
   JIA-211 GRADUATION GALLERY — APP LOGIC
   Pure vanilla JS. No frameworks, no build step.
   ========================================================= */
(function () {
  'use strict';

  /* ---------------- STATE ---------------- */
  const state = {
    meta: null,
    categories: [],
    people: [],
    photos: [],          // full dataset
    filtered: [],         // after search/category/person filter + sort
    renderedCount: 0,
    batchSize: 28,
    sort: 'recent',
    category: 'all',
    person: 'all',
    query: '',
    lightboxIndex: -1,
    slideshow: { active: false, timer: null, delay: 3200 },
  };

  const $ = (sel, ctx) => (ctx || document).querySelector(sel);
  const $$ = (sel, ctx) => Array.from((ctx || document).querySelectorAll(sel));

  const catById = id => state.categories.find(c => c.id === id);
  const personById = id => state.people.find(p => p.id === id);

  /* ---------------- REAL IMAGE PATHS ----------------
     photos/{folder}/{file}.webp and thumbs/{folder}/{file}.webp
     Nothing here is hardcoded — folder/file always come from
     data/photos.json, which is itself generated by scanning disk. */
  const thumbSrc = photo => `thumbs/${photo.folder}/${photo.file}`;
  const fullSrc = photo => `photos/${photo.folder}/${photo.file}`;

  /* Attaches a graceful fallback chain to an <img>: if the real file
     isn't there yet (e.g. before photos/thumbs have been populated),
     fall back to a generated placeholder instead of a broken image.
     Guarded so it only ever fires once per element. */
  function withFallback(img, getFallbackSrc) {
    img.addEventListener(
      'error',
      () => {
        if (img.dataset.fallenBack) return;
        img.dataset.fallenBack = '1';
        img.src = getFallbackSrc();
      },
      { once: true }
    );
    return img;
  }

  /* ---------------- LOOKUP INDICES (perf) ----------------
     Built once after data loads so category/person filtering doesn't
     require scanning the full photo array on every interaction. */
  const indices = { byCategory: new Map(), byPerson: new Map() };
  function buildIndices() {
    indices.byCategory.clear();
    indices.byPerson.clear();
    state.categories.forEach(c => indices.byCategory.set(c.id, []));
    state.people.forEach(p => indices.byPerson.set(p.id, []));
    state.photos.forEach(photo => {
      indices.byCategory.get(photo.cat)?.push(photo);
      indices.byPerson.get(photo.person)?.push(photo);
    });
  }

  /* ---------------- INIT ---------------- */
  document.addEventListener('DOMContentLoaded', init);

  async function init() {
    buildHeroParticles();
    initDrawer();
    initSectionScrollSpy();
    initSlideshowButton();
    initSearch();
    initLightbox();

    try {
      const res = await fetch('data/photos.json');
      if (!res.ok) throw new Error('data fetch failed: ' + res.status);
      const data = await res.json();
      state.meta = data.meta;
      state.categories = data.categories;
      state.people = data.people;
      state.photos = data.photos;
      buildIndices();

      renderCategoryGrid();
      renderPeopleList();
      renderDownloads();
      populateFilters();
      applyFilters(); // builds state.filtered + renders first batch
      animateCounters();
      syncSizeStats();
      initInfiniteScroll();
    } catch (err) {
      console.error(err);
      showToast('Деректерді жүктеу кезінде қате орын алды.');
    } finally {
      hideLoader();
    }
  }

  function hideLoader() {
    const loader = $('#loader');
    setTimeout(() => loader && loader.classList.add('hide'), 350);
  }

  /* ---------------- HERO PARTICLES ---------------- */
  function buildHeroParticles() {
    const wrap = $('#heroParticles');
    if (!wrap) return;
    const count = window.innerWidth < 700 ? 14 : 28;
    for (let i = 0; i < count; i++) {
      const span = document.createElement('span');
      const left = Math.random() * 100;
      const delay = Math.random() * 8;
      const duration = 6 + Math.random() * 8;
      const bottom = Math.random() * 40;
      span.style.left = left + '%';
      span.style.bottom = bottom + 'px';
      span.style.animationDelay = delay + 's';
      span.style.animationDuration = duration + 's';
      wrap.appendChild(span);
    }
  }

  /* ---------------- COUNTERS ---------------- */
  function animateCounters() {
    $$('[data-count]').forEach(el => {
      const target = parseInt(el.getAttribute('data-count'), 10);
      const duration = 1400;
      const start = performance.now();
      function tick(now) {
        const p = Math.min(1, (now - start) / duration);
        const eased = 1 - Math.pow(1 - p, 3);
        el.textContent = Math.round(target * eased).toLocaleString('ru-RU');
        if (p < 1) requestAnimationFrame(tick);
        else el.textContent = target.toLocaleString('ru-RU');
      }
      requestAnimationFrame(tick);
    });
  }

  function syncSizeStats() {
    const label = formatSize(state.meta);
    const sidebar = $('#sidebarSize');
    const about = $('#aboutSize');
    if (sidebar) sidebar.textContent = label;
    if (about) about.textContent = label;
  }

  /* ---------------- CATEGORY GRID ---------------- */
  function renderCategoryGrid() {
    const grid = $('#categoryGrid');
    if (!grid) return;
    grid.innerHTML = '';
    state.categories.forEach(cat => {
      const card = document.createElement('div');
      card.className = 'category-card';
      card.innerHTML = `
        <img class="cat-cover" alt="${escapeHtml(cat.name)}">
        <div class="category-card-arrow"><svg viewBox="0 0 24 24"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div>
        <div class="category-card-body">
          <span class="category-card-count">${cat.icon} ${cat.count.toLocaleString('ru-RU')} фото</span>
          <div class="category-card-title">${escapeHtml(cat.name)}</div>
        </div>`;
      const img = card.querySelector('.cat-cover');
      img.loading = 'lazy';
      img.decoding = 'async';
      const fallback = () => window.Placeholder.categoryCoverPlaceholder({ id: cat.id, cat: cat.id, hue: hueForCat(cat.id) });
      img.src = cat.cover || fallback();
      if (cat.cover) withFallback(img, fallback);
      card.addEventListener('click', () => {
        state.category = cat.id;
        $('#categoryFilter').value = cat.id;
        applyFilters();
        scrollToSection('gallery');
      });
      grid.appendChild(card);
    });
  }

  function hueForCat(id) {
    const map = { mania: 40, free: 190, girls: 320, boys: 205, all: 45, group: 275 };
    return map[id] !== undefined ? map[id] : 40;
  }

  /* ---------------- PEOPLE LIST ---------------- */
  function renderPeopleList() {
    const list = $('#peopleList');
    if (!list) return;
    list.innerHTML = '';
    state.people.forEach(p => {
      const row = document.createElement('div');
      row.className = 'person-row';
      row.innerHTML = `
        <img class="person-avatar" alt="${escapeHtml(p.name)}">
        <div>
          <div class="person-name">${escapeHtml(p.name)}</div>
          <div class="person-count">${p.count} фотосурет</div>
        </div>
        <div class="person-row-right">
          <span class="person-count-badge">${Math.round((p.count / state.meta.totalPhotos) * 100)}%</span>
        </div>`;
      const avatarImg = row.querySelector('.person-avatar');
      avatarImg.loading = 'lazy';
      avatarImg.decoding = 'async';
      const fallback = () => window.Placeholder.avatarPlaceholder({ id: p.id, name: p.name });
      avatarImg.src = p.thumbnail || fallback();
      if (p.thumbnail) withFallback(avatarImg, fallback);
      row.addEventListener('click', () => {
        state.person = p.id;
        $('#personFilter').value = p.id;
        applyFilters();
        scrollToSection('gallery');
      });
      list.appendChild(row);
    });
  }

  /* ---------------- DOWNLOADS ---------------- */
  function renderDownloads() {
    const grid = $('#downloadGrid');
    if (!grid) return;
    grid.innerHTML = '';

    const zipIcon = `<svg viewBox="0 0 24 24"><path d="M4 4h16v16H4z"/><path d="M9 4v16M9 7h3M9 11h3M9 15h3"/></svg>`;

    const cards = [
      { title: 'Барлық фотолар', meta: `${state.meta.totalPhotos.toLocaleString('ru-RU')} фото · ${formatSize(state.meta)}`, path: 'downloads/all-photos.zip', primary: true },
      ...state.categories.map(c => ({
        title: c.name,
        meta: `${c.count.toLocaleString('ru-RU')} фото`,
        path: `downloads/${c.id}.zip`,
      })),
    ];

    cards.forEach(c => {
      const card = document.createElement('div');
      card.className = 'download-card' + (c.primary ? ' primary' : '');
      card.innerHTML = `
        <div class="download-icon">${zipIcon}</div>
        <div>
          <div class="download-card-title">${escapeHtml(c.title)}</div>
          <div class="download-card-meta">${c.meta}</div>
        </div>
        <button class="btn ${c.primary ? 'btn-gold' : 'btn-outline'}">ZIP жүктеу</button>`;
      card.querySelector('button').addEventListener('click', () => downloadArchive(c.path, c.title));
      grid.appendChild(card);
    });

    const peopleList = $('#downloadPeopleList');
    peopleList.innerHTML = '';
    state.people.forEach(p => {
      const chip = document.createElement('div');
      chip.className = 'dl-person-chip';
      chip.innerHTML = `<img alt=""> <span>${escapeHtml(p.name)} · ${p.count}</span>`;
      const chipImg = chip.querySelector('img');
      chipImg.loading = 'lazy';
      chipImg.decoding = 'async';
      const fallback = () => window.Placeholder.avatarPlaceholder({ id: p.id, name: p.name });
      chipImg.src = p.thumbnail || fallback();
      if (p.thumbnail) withFallback(chipImg, fallback);
      chip.addEventListener('click', () => downloadArchive(`downloads/people/${p.id}.zip`, p.name));
      peopleList.appendChild(chip);
    });
  }

  async function downloadArchive(path, label) {
    showToast(`«${label}» дайындалуда…`);
    try {
      const res = await fetch(path, { method: 'HEAD' });
      if (res.ok) {
        const a = document.createElement('a');
        a.href = path;
        a.download = '';
        document.body.appendChild(a);
        a.click();
        a.remove();
        showToast(`«${label}» жүктелуде ✓`);
        return;
      }
      throw new Error('not found');
    } catch (e) {
      showToast(`Мұрағат әлі қосылған жоқ. Файлды ${path} жолына қойыңыз.`);
    }
  }

  /* ---------------- FILTERS / SELECTS ---------------- */
  function populateFilters() {
    const catSel = $('#categoryFilter');
    state.categories.forEach(c => {
      const opt = document.createElement('option');
      opt.value = c.id;
      opt.textContent = `${c.name} (${c.count})`;
      catSel.appendChild(opt);
    });
    const personSel = $('#personFilter');
    state.people.forEach(p => {
      const opt = document.createElement('option');
      opt.value = p.id;
      opt.textContent = `${p.name} (${p.count})`;
      personSel.appendChild(opt);
    });

    catSel.addEventListener('change', () => { state.category = catSel.value; applyFilters(); });
    personSel.addEventListener('change', () => { state.person = personSel.value; applyFilters(); });

    $$('#sortChips .chip').forEach(chip => {
      chip.addEventListener('click', () => {
        $$('#sortChips .chip').forEach(c => c.classList.remove('active'));
        chip.classList.add('active');
        state.sort = chip.getAttribute('data-sort');
        applyFilters();
      });
    });
  }

  /* ---------------- SEARCH ---------------- */
  function initSearch() {
    const input = $('#searchInput');
    if (!input) return;
    let t;
    input.addEventListener('input', () => {
      clearTimeout(t);
      t = setTimeout(() => {
        state.query = input.value.trim().toLowerCase();
        applyFilters();
      }, 200);
    });
    document.addEventListener('keydown', e => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        input.focus();
      }
    });
  }

  function matchesQuery(photo, q) {
    if (!q) return true;
    const cat = catById(photo.cat);
    const person = personById(photo.person);
    return (
      (cat && cat.name.toLowerCase().includes(q)) ||
      (person && person.name.toLowerCase().includes(q)) ||
      photo.folder.toLowerCase().includes(q) ||
      photo.date.includes(q) ||
      photo.id.includes(q)
    );
  }

  /* ---------------- APPLY FILTERS + SORT ---------------- */
  function applyFilters() {
    // Start from the smallest relevant precomputed bucket instead of
    // scanning the entire dataset — meaningful once the archive grows
    // well beyond a couple hundred photos.
    let base = state.photos;
    if (state.person !== 'all') {
      base = indices.byPerson.get(state.person) || [];
    } else if (state.category !== 'all') {
      base = indices.byCategory.get(state.category) || [];
    }

    let list = base.filter(p => {
      if (state.category !== 'all' && p.cat !== state.category) return false;
      if (state.person !== 'all' && p.person !== state.person) return false;
      if (!matchesQuery(p, state.query)) return false;
      return true;
    });

    if (state.sort === 'recent') {
      list = list.slice().sort((a, b) => (a.date < b.date ? 1 : -1));
    } else if (state.sort === 'viewed') {
      list = list.slice().sort((a, b) => b.views - a.views);
    } else if (state.sort === 'random') {
      list = shuffle(list.slice());
    }

    state.filtered = list;
    state.renderedCount = 0;
    $('#photoGrid').innerHTML = '';
    $('#endMessage').hidden = true;
    $('#resultsCount').textContent = `${list.length.toLocaleString('ru-RU')} фото табылды`;
    renderNextBatch();
  }

  function shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }

  /* ---------------- PHOTO GRID RENDER (lazy batches) ---------------- */
  function renderNextBatch() {
    const grid = $('#photoGrid');
    const start = state.renderedCount;
    const end = Math.min(state.filtered.length, start + state.batchSize);
    if (start >= state.filtered.length) {
      $('#endMessage').hidden = state.filtered.length === 0;
      return;
    }

    const frag = document.createDocumentFragment();
    for (let i = start; i < end; i++) {
      frag.appendChild(buildPhotoCard(state.filtered[i], i));
    }
    grid.appendChild(frag);
    state.renderedCount = end;

    if (state.renderedCount >= state.filtered.length) {
      $('#endMessage').hidden = false;
    }
  }

  function buildPhotoCard(photo, index) {
    const cat = catById(photo.cat);
    const person = personById(photo.person);
    const card = document.createElement('div');
    card.className = 'photo-card';
    card.style.animationDelay = (Math.random() * 0.15) + 's';
    card.innerHTML = `
      <img loading="lazy" alt="${cat ? escapeHtml(cat.name) : ''}">
      <span class="photo-card-views">👁 ${photo.views.toLocaleString('ru-RU')}</span>
      <div class="photo-card-overlay">
        <div class="photo-card-meta">
          <span class="photo-card-tag">${person ? escapeHtml(person.name) : ''}</span>
          <button class="photo-card-dl" title="Жүктеу"><svg viewBox="0 0 24 24"><path d="M12 3v10m0 0-3.5-3.5M12 13l3.5-3.5"/><path d="M5 18h14"/></svg></button>
        </div>
      </div>`;
    const img = card.querySelector('img');
    img.decoding = 'async';
    const fallback = () => window.Placeholder.photoPlaceholder({ id: photo.id, cat: photo.cat, hue: hashHue(photo.id), w: 4, h: 3 });
    img.src = thumbSrc(photo);
    withFallback(img, fallback);

    card.addEventListener('click', () => openLightbox(state.filtered, index));
    card.querySelector('.photo-card-dl').addEventListener('click', e => {
      e.stopPropagation();
      downloadSinglePhoto(photo);
    });
    return card;
  }

  function hashHue(str) {
    let h = 0;
    for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
    return h % 360;
  }

  async function downloadSinglePhoto(photo) {
    const path = fullSrc(photo);
    try {
      const res = await fetch(path, { method: 'HEAD' });
      if (!res.ok) throw new Error('not found');
    } catch (e) {
      showToast(`Файл табылмады: ${path}`);
      return;
    }
    const a = document.createElement('a');
    a.href = path;
    a.download = photo.file;
    document.body.appendChild(a);
    a.click();
    a.remove();
    showToast('Фотосурет жүктелді ✓');
  }

  /* ---------------- INFINITE SCROLL ---------------- */
  function initInfiniteScroll() {
    const sentinel = $('#gridSentinel');
    const loadingEl = $('#loadingMore');
    if (!sentinel) return;
    const obs = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (entry.isIntersecting && state.renderedCount < state.filtered.length) {
          loadingEl.classList.add('show');
          setTimeout(() => {
            renderNextBatch();
            loadingEl.classList.remove('show');
          }, 380);
        }
      });
    }, { rootMargin: '600px 0px' });
    obs.observe(sentinel);
  }

  /* ---------------- LIGHTBOX ---------------- */
  let lbList = [];

  function initLightbox() {
    $('#lbClose').addEventListener('click', closeLightbox);
    $('#lbPrev').addEventListener('click', () => stepLightbox(-1));
    $('#lbNext').addEventListener('click', () => stepLightbox(1));
    $('#lbFullscreen').addEventListener('click', toggleFullscreen);
    $('#lbDownload').addEventListener('click', () => {
      const photo = lbList[state.lightboxIndex];
      if (photo) downloadSinglePhoto(photo);
    });
    $('#lbSlideshow').addEventListener('click', () => toggleSlideshow(true));
    $('#lightbox').addEventListener('click', e => {
      if (e.target.id === 'lightbox' || e.target.classList.contains('lightbox-stage')) closeLightbox();
    });
    document.addEventListener('keydown', e => {
      if (!$('#lightbox').classList.contains('open')) return;
      if (e.key === 'Escape') closeLightbox();
      if (e.key === 'ArrowLeft') stepLightbox(-1);
      if (e.key === 'ArrowRight') stepLightbox(1);
    });
  }

  function openLightbox(list, index) {
    lbList = list;
    state.lightboxIndex = index;
    renderLightbox();
    $('#lightbox').classList.add('open');
    document.body.style.overflow = 'hidden';
  }

  function renderLightbox() {
    const photo = lbList[state.lightboxIndex];
    if (!photo) return;
    const cat = catById(photo.cat);
    const person = personById(photo.person);

    const img = $('#lbImage');
    delete img.dataset.fallenBack;
    img.onerror = () => {
      // full-res missing -> try thumb -> generated placeholder
      if (img.dataset.stage === 'thumb') {
        img.onerror = null;
        img.src = window.Placeholder.photoPlaceholder({ id: photo.id, cat: photo.cat, hue: hashHue(photo.id), w: 4, h: 3 });
      } else {
        img.dataset.stage = 'thumb';
        img.src = thumbSrc(photo);
      }
    };
    img.dataset.stage = 'full';
    img.src = fullSrc(photo);

    $('#lbCategory').textContent = cat ? cat.name : '—';
    $('#lbPerson').textContent = person ? person.name : '—';
    $('#lbDate').textContent = photo.date;
  }

  function stepLightbox(dir) {
    if (!lbList.length) return;
    state.lightboxIndex = (state.lightboxIndex + dir + lbList.length) % lbList.length;
    renderLightbox();
  }

  function closeLightbox() {
    $('#lightbox').classList.remove('open');
    document.body.style.overflow = '';
    toggleSlideshow(false);
    if (document.fullscreenElement) document.exitFullscreen().catch(() => {});
  }

  function toggleFullscreen() {
    const stage = $('#lightbox');
    if (!document.fullscreenElement) {
      stage.requestFullscreen?.().catch(() => showToast('Толық экран режимі қолдау таппады.'));
    } else {
      document.exitFullscreen();
    }
  }

  /* ---------------- SLIDESHOW ---------------- */
  function initSlideshowButton() {
    $('#slideshowBtn')?.addEventListener('click', () => {
      if (!state.filtered.length) return;
      openLightbox(state.filtered, 0);
      toggleSlideshow(true);
    });
  }

  function toggleSlideshow(forceOn) {
    const shouldPlay = forceOn !== undefined ? forceOn : !state.slideshow.active;
    state.slideshow.active = shouldPlay;
    const progress = $('#lbProgress');
    if (shouldPlay) {
      progress.hidden = false;
      runSlideshowTick();
    } else {
      progress.hidden = true;
      clearTimeout(state.slideshow.timer);
      progress.querySelector('span').style.transition = 'none';
      progress.querySelector('span').style.width = '0%';
    }
  }

  function runSlideshowTick() {
    const bar = $('#lbProgress span');
    bar.style.transition = 'none';
    bar.style.width = '0%';
    requestAnimationFrame(() => {
      bar.style.transition = `width ${state.slideshow.delay}ms linear`;
      bar.style.width = '100%';
    });
    state.slideshow.timer = setTimeout(() => {
      if (!state.slideshow.active) return;
      stepLightbox(1);
      runSlideshowTick();
    }, state.slideshow.delay);
  }

  /* ---------------- MOBILE DRAWER ---------------- */
  function initDrawer() {
    const sidebar = $('#sidebar');
    const overlay = $('#drawerOverlay');
    const openBtn = $('#drawerOpen');
    if (!sidebar) return;
    function open() { sidebar.classList.add('open'); overlay.classList.add('show'); }
    function close() { sidebar.classList.remove('open'); overlay.classList.remove('show'); }
    openBtn?.addEventListener('click', open);
    overlay?.addEventListener('click', close);
    $$('.nav-link, .bn-item').forEach(link => link.addEventListener('click', close));
  }

  /* ---------------- SECTION SCROLLSPY / NAV ---------------- */
  function scrollToSection(id) {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  }

  function initSectionScrollSpy() {
    $$('[data-section-link]').forEach(a => {
      a.addEventListener('click', e => {
        e.preventDefault();
        scrollToSection(a.getAttribute('data-section-link'));
      });
    });

    const sections = ['home', 'gallery', 'people', 'categories', 'downloads', 'about']
      .map(id => document.getElementById(id))
      .filter(Boolean);

    const navLinks = $$('.nav-link, .bn-item');

    const obs = new IntersectionObserver(
      entries => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            const id = entry.target.id;
            navLinks.forEach(link => {
              link.classList.toggle('active', link.getAttribute('data-section') === id);
            });
          }
        });
      },
      { rootMargin: '-40% 0px -50% 0px', threshold: 0 }
    );
    sections.forEach(s => obs.observe(s));

    navLinks.forEach(link => {
      link.addEventListener('click', e => {
        const id = link.getAttribute('data-section');
        if (id) {
          e.preventDefault();
          scrollToSection(id);
        }
      });
    });
  }

  /* ---------------- TOAST ---------------- */
  let toastTimer;
  function showToast(msg) {
    const el = $('#toast');
    if (!el) return;
    el.textContent = msg;
    el.classList.add('show');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => el.classList.remove('show'), 3200);
  }

  /* ---------------- UTIL ---------------- */
  function formatSize(meta) {
    const bytes = meta && meta.originalSizeBytes;
    if (!bytes) return `~${meta.originalSizeGB} GB`;
    if (bytes < 1024 ** 3) return `${(bytes / 1024 ** 2).toFixed(1)} MB`;
    return `~${(bytes / 1024 ** 3).toFixed(1)} GB`;
  }

  function escapeHtml(str) {
    return String(str).replace(/[&<>"']/g, m => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
    }[m]));
  }
})();
